version: '2'

networks:
  basic:

services:
  ca0:
    image: hyperledger/fabric-ca:1.4.3
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/202010a052163db742d327e2729d59459a08f2c71fee852a74e6c3ae8cc29474_sk
      # Enable TLS
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/202010a052163db742d327e2729d59459a08f2c71fee852a74e6c3ae8cc29474_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/202010a052163db742d327e2729d59459a08f2c71fee852a74e6c3ae8cc29474_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1
    networks:
      - basic

  ca1:
    image: hyperledger/fabric-ca:1.4.3
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/07cbf95a9297a07f920b66f1da3586509ac9005271d6ded1bc231564bf74667a_sk
      # Enable TLS
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/07cbf95a9297a07f920b66f1da3586509ac9005271d6ded1bc231564bf74667a_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/07cbf95a9297a07f920b66f1da3586509ac9005271d6ded1bc231564bf74667a_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg2
    networks:
      - basic


  orderer.example.com:
    extends:
      file: docker-compose-orderer.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    networks:
      - basic

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file: docker-compose-org1.yaml
      service: peer0.org1.example.com
    networks:
      - basic
  
  peer1.org1.example.com:
    container_name: peer1.org1.example.com
    extends:
      file: docker-compose-org1.yaml
      service: peer1.org1.example.com
    networks:
      - basic

  
  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    extends:
      file: docker-compose-org2.yaml
      service: peer0.org2.example.com
    networks:
      - basic
  
  peer1.org2.example.com:
    container_name: peer1.org2.example.com
    extends:
      file: docker-compose-org2.yaml
      service: peer1.org2.example.com
    networks:
      - basic